// <auto-generated />
using System;
using App05.Dati;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App05.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20260428105213_TipoContattoOpzionale")]
    partial class TipoContattoOpzionale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("App05.Dati.Strutture.Contatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Contatti");
                });

            modelBuilder.Entity("App05.Dati.Strutture.Gruppo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gruppi");
                });

            modelBuilder.Entity("App05.Dati.Strutture.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tipi");
                });

            modelBuilder.Entity("ContattoGruppo", b =>
                {
                    b.Property<int>("ContattiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GruppiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContattiId", "GruppiId");

                    b.HasIndex("GruppiId");

                    b.ToTable("ContattoGruppo");
                });

            modelBuilder.Entity("App05.Dati.Strutture.Contatto", b =>
                {
                    b.HasOne("App05.Dati.Strutture.Tipo", "Tipo")
                        .WithMany("Contatti")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ContattoGruppo", b =>
                {
                    b.HasOne("App05.Dati.Strutture.Contatto", null)
                        .WithMany()
                        .HasForeignKey("ContattiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App05.Dati.Strutture.Gruppo", null)
                        .WithMany()
                        .HasForeignKey("GruppiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App05.Dati.Strutture.Tipo", b =>
                {
                    b.Navigation("Contatti");
                });
#pragma warning restore 612, 618
        }
    }
}
