
// This file was auto-generated by ML.NET Model Builder. 

using Riconoscitore_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
Riconoscitore.ModelInput sampleData = new Riconoscitore.ModelInput()
{
    Description = @"XPath.XDocument navigator doesn't support MoveToId(string).  Verify if this was ever supported. If it was, verify if we want to support it in the future. If it wasn't move the tests to a different file and remove them from XPath.XDocument.Tests project.  Failing tests: NodeSetFunctionsTest2267 MatchesTest2352  <!--- @huboard:{""order"":20.0,""milestone_order"":20,""custom_state"":""""} -->",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Area with predicted Area from sample data...\n\n");


Console.WriteLine($"Area: {@"area-System.Xml"}");
Console.WriteLine($"Description: {@"XPath.XDocument navigator doesn't support MoveToId(string).  Verify if this was ever supported. If it was, verify if we want to support it in the future. If it wasn't move the tests to a different file and remove them from XPath.XDocument.Tests project.  Failing tests: NodeSetFunctionsTest2267 MatchesTest2352  <!--- @huboard:{""order"":20.0,""milestone_order"":20,""custom_state"":""""} -->"}");


var sortedScoresWithLabel = Riconoscitore.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

